version: '3.7'
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  app:
    build: .
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - .:/nodesample
      - node_modules:/nodesample/node_modules
    depends_on:
      - db
      - redis

volumes:
  node_modules:
  postgres:
  redis:
